// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCF8VIe21eflYlAg2QXl5FZ1_8bme4lLc',
    appId: '1:1050870201307:web:006a55e21fbb48358105fe',
    messagingSenderId: '1050870201307',
    projectId: 'chatapp-ce8',
    authDomain: 'chatapp-ce8.firebaseapp.com',
    storageBucket: 'chatapp-ce8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLPrDKENMzv2oqhxlBjQPui_rO3CcULn8',
    appId: '1:1050870201307:android:56eff15cded065c18105fe',
    messagingSenderId: '1050870201307',
    projectId: 'chatapp-ce8',
    storageBucket: 'chatapp-ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD57ByJD3qGTmmIFqSNA7aA2rR64oISKwI',
    appId: '1:1050870201307:ios:c0440397cda788658105fe',
    messagingSenderId: '1050870201307',
    projectId: 'chatapp-ce8',
    storageBucket: 'chatapp-ce8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD57ByJD3qGTmmIFqSNA7aA2rR64oISKwI',
    appId: '1:1050870201307:ios:e7a976d18f4630e98105fe',
    messagingSenderId: '1050870201307',
    projectId: 'chatapp-ce8',
    storageBucket: 'chatapp-ce8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
